/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/主持人队': RouteRecordInfo<
      '/posts/主持人队',
      '/posts/%E4%B8%BB%E6%8C%81%E4%BA%BA%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/广播站': RouteRecordInfo<
      '/posts/广播站',
      '/posts/%E5%B9%BF%E6%92%AD%E7%AB%99',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/摄协-new': RouteRecordInfo<
      '/posts/摄协-new',
      '/posts/%E6%91%84%E5%8D%8F-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/桂中跑团': RouteRecordInfo<
      '/posts/桂中跑团',
      '/posts/%E6%A1%82%E4%B8%AD%E8%B7%91%E5%9B%A2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/电视台': RouteRecordInfo<
      '/posts/电视台',
      '/posts/%E7%94%B5%E8%A7%86%E5%8F%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/经济社-new': RouteRecordInfo<
      '/posts/经济社-new',
      '/posts/%E7%BB%8F%E6%B5%8E%E7%A4%BE-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TGX-new': RouteRecordInfo<
      '/posts/TGX-new',
      '/posts/TGX-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_e1f7893fbde291f763a7e8f6b7c0785e/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/主持人队.md': {
      routes:
        | '/posts/主持人队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/广播站.md': {
      routes:
        | '/posts/广播站'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/摄协-new.md': {
      routes:
        | '/posts/摄协-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/桂中跑团.md': {
      routes:
        | '/posts/桂中跑团'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/电视台.md': {
      routes:
        | '/posts/电视台'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/经济社-new.md': {
      routes:
        | '/posts/经济社-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/TGX-new.md': {
      routes:
        | '/posts/TGX-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
