/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/主持人队': RouteRecordInfo<
      '/posts/主持人队',
      '/posts/%E4%B8%BB%E6%8C%81%E4%BA%BA%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/乒乓球队': RouteRecordInfo<
      '/posts/乒乓球队',
      '/posts/%E4%B9%92%E4%B9%93%E7%90%83%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/传媒社': RouteRecordInfo<
      '/posts/传媒社',
      '/posts/%E4%BC%A0%E5%AA%92%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/创客部': RouteRecordInfo<
      '/posts/创客部',
      '/posts/%E5%88%9B%E5%AE%A2%E9%83%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/听颂中文辩论队': RouteRecordInfo<
      '/posts/听颂中文辩论队',
      '/posts/%E5%90%AC%E9%A2%82%E4%B8%AD%E6%96%87%E8%BE%A9%E8%AE%BA%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/咏春社': RouteRecordInfo<
      '/posts/咏春社',
      '/posts/%E5%92%8F%E6%98%A5%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/团委': RouteRecordInfo<
      '/posts/团委',
      '/posts/%E5%9B%A2%E5%A7%94',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/在路上文学社': RouteRecordInfo<
      '/posts/在路上文学社',
      '/posts/%E5%9C%A8%E8%B7%AF%E4%B8%8A%E6%96%87%E5%AD%A6%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/学生会': RouteRecordInfo<
      '/posts/学生会',
      '/posts/%E5%AD%A6%E7%94%9F%E4%BC%9A',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/广播站': RouteRecordInfo<
      '/posts/广播站',
      '/posts/%E5%B9%BF%E6%92%AD%E7%AB%99',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/心理社': RouteRecordInfo<
      '/posts/心理社',
      '/posts/%E5%BF%83%E7%90%86%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/摄协-new': RouteRecordInfo<
      '/posts/摄协-new',
      '/posts/%E6%91%84%E5%8D%8F-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/校舞蹈队': RouteRecordInfo<
      '/posts/校舞蹈队',
      '/posts/%E6%A0%A1%E8%88%9E%E8%B9%88%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/桂中跑团': RouteRecordInfo<
      '/posts/桂中跑团',
      '/posts/%E6%A1%82%E4%B8%AD%E8%B7%91%E5%9B%A2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/模拟联合国': RouteRecordInfo<
      '/posts/模拟联合国',
      '/posts/%E6%A8%A1%E6%8B%9F%E8%81%94%E5%90%88%E5%9B%BD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/毽球队': RouteRecordInfo<
      '/posts/毽球队',
      '/posts/%E6%AF%BD%E7%90%83%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/漫研社': RouteRecordInfo<
      '/posts/漫研社',
      '/posts/%E6%BC%AB%E7%A0%94%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/物理竞赛社': RouteRecordInfo<
      '/posts/物理竞赛社',
      '/posts/%E7%89%A9%E7%90%86%E7%AB%9E%E8%B5%9B%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/电影社': RouteRecordInfo<
      '/posts/电影社',
      '/posts/%E7%94%B5%E5%BD%B1%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/电视台': RouteRecordInfo<
      '/posts/电视台',
      '/posts/%E7%94%B5%E8%A7%86%E5%8F%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/经济社-new': RouteRecordInfo<
      '/posts/经济社-new',
      '/posts/%E7%BB%8F%E6%B5%8E%E7%A4%BE-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/羽毛球社': RouteRecordInfo<
      '/posts/羽毛球社',
      '/posts/%E7%BE%BD%E6%AF%9B%E7%90%83%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/英语辩论队': RouteRecordInfo<
      '/posts/英语辩论队',
      '/posts/%E8%8B%B1%E8%AF%AD%E8%BE%A9%E8%AE%BA%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/街舞社': RouteRecordInfo<
      '/posts/街舞社',
      '/posts/%E8%A1%97%E8%88%9E%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/青创社': RouteRecordInfo<
      '/posts/青创社',
      '/posts/%E9%9D%92%E5%88%9B%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/食堂宵夜': RouteRecordInfo<
      '/posts/食堂宵夜',
      '/posts/%E9%A3%9F%E5%A0%82%E5%AE%B5%E5%A4%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ACE韩舞社': RouteRecordInfo<
      '/posts/ACE韩舞社',
      '/posts/ACE%E9%9F%A9%E8%88%9E%E7%A4%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Band乐队': RouteRecordInfo<
      '/posts/Band乐队',
      '/posts/Band%E4%B9%90%E9%98%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TGX-new': RouteRecordInfo<
      '/posts/TGX-new',
      '/posts/TGX-new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_e1f7893fbde291f763a7e8f6b7c0785e/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/主持人队.md': {
      routes:
        | '/posts/主持人队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/乒乓球队.md': {
      routes:
        | '/posts/乒乓球队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/传媒社.md': {
      routes:
        | '/posts/传媒社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/创客部.md': {
      routes:
        | '/posts/创客部'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/听颂中文辩论队.md': {
      routes:
        | '/posts/听颂中文辩论队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/咏春社.md': {
      routes:
        | '/posts/咏春社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/团委.md': {
      routes:
        | '/posts/团委'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/在路上文学社.md': {
      routes:
        | '/posts/在路上文学社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/学生会.md': {
      routes:
        | '/posts/学生会'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/广播站.md': {
      routes:
        | '/posts/广播站'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/心理社.md': {
      routes:
        | '/posts/心理社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/摄协-new.md': {
      routes:
        | '/posts/摄协-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/校舞蹈队.md': {
      routes:
        | '/posts/校舞蹈队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/桂中跑团.md': {
      routes:
        | '/posts/桂中跑团'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/模拟联合国.md': {
      routes:
        | '/posts/模拟联合国'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/毽球队.md': {
      routes:
        | '/posts/毽球队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/漫研社.md': {
      routes:
        | '/posts/漫研社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/物理竞赛社.md': {
      routes:
        | '/posts/物理竞赛社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/电影社.md': {
      routes:
        | '/posts/电影社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/电视台.md': {
      routes:
        | '/posts/电视台'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/经济社-new.md': {
      routes:
        | '/posts/经济社-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/羽毛球社.md': {
      routes:
        | '/posts/羽毛球社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/英语辩论队.md': {
      routes:
        | '/posts/英语辩论队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/街舞社.md': {
      routes:
        | '/posts/街舞社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/青创社.md': {
      routes:
        | '/posts/青创社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/食堂宵夜.md': {
      routes:
        | '/posts/食堂宵夜'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ACE韩舞社.md': {
      routes:
        | '/posts/ACE韩舞社'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Band乐队.md': {
      routes:
        | '/posts/Band乐队'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/TGX-new.md': {
      routes:
        | '/posts/TGX-new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
